// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

(String, String) getJapChar({required BigInt index}) =>
    RustLib.instance.api.crateApiJapCharGetJapChar(index: index);

BigInt rand045() => RustLib.instance.api.crateApiJapCharRand045();

List<String> charVec() => RustLib.instance.api.crateApiJapCharCharVec();

(String, String) splitJapChar({required String japChar}) =>
    RustLib.instance.api.crateApiJapCharSplitJapChar(japChar: japChar);
